on:
  schedule:
    - cron: "0 12 * * *"
name: Stale Bot workflow
jobs:
  build:
    name: stale
    runs-on: ubuntu-latest
    steps:
      - name: stale
        id: stale
        uses: yanhao-li/stale@v2.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DAYS_BEFORE_STALE: 1
          DAYS_BEFORE_CLOSE: 1
          DRY_RUN: false
          OPERATIONS_PER_RUN: 5000
          STALE_ISSUE_MESSAGE: |
            Hi!
            Since this issue has been inactivity for 2 months, I'm going to tag this issue with `stale`, and it will be closed next month.
            If we missed this issue or if you want to keep it open, please reply here. You can also add the label "not stale" to keep this issue open!
          CLOSE_MESSAGE: |
            Hello again!
            It's been one month since this issue was tagged `stale`, this issue is going to be closed.
            Please feel free to reopen this issue or create a new one if you need anything else.
          EXEMPT_ISSUE_LABELS: |
            not stale
            important
            good first issue
            no triage
            status: confirmed
